# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - apt-transport-https
      - libgmp-dev
      - dart # Install Dart which is required for dart-sass

# Download and unpack the stack and dart-sass executables
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_retry curl -L https://github.com/sass/dart-sass/releases/download/1.14.2/dart-sass-1.14.2-linux-x64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/sass'

script: travis_wait 30 scripts/build.sh

before_deploy:
- openssl aes-256-cbc -K $encrypted_1fe6220ef9db_key -iv $encrypted_1fe6220ef9db_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- mv deploy_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master
